version: "3"

services:
  # Treafik Proxy
  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik:ro
      - "./letsencrypt:/letsencrypt"
    networks:
      - traefik_proxy
      - default
    ports:
      - 80:80
      - 8080:8080

  # Main site
  portfolio:
    build:
      context: ./static
      args:
        giturl: ${GIT_URL}
    labels:
      - "traefik.http.routers.portfolio.rule=Host(`${HOST}`) && PathPrefix(`/`)"
      - "traefik.http.routers.portfolio.tls=${USE_TLS}"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"

  # Online SSH Client
  sshwifty:
    image: niruix/sshwifty:latest
    environment:
      - SSHWIFTY_SHAREDKEY=${SERVICE_PASSWORD}
    labels:
      - "traefik.http.routers.sshwifty.rule=Host(`ssh.${HOST}`)"
      - "traefik.http.routers.sshwifty.tls=${USE_TLS}"
      - "traefik.http.routers.sshwifty.tls.certresolver=letsencrypt"

  # Online website proxy
  proxy:
    image: p3ntest/nodeproxy
    environment:
      - USERNAME=admin
      - PASSWORD=${SERVICE_PASSWORD}
    labels:
      - "traefik.http.routers.webproxy.rule=Host(`proxy.${HOST}`)"
      - "traefik.http.routers.webproxy.tls=${USE_TLS}"
      - "traefik.http.routers.webproxy.tls.certresolver=letsencrypt"

  # Url shortener
  urlredis:
    image: redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - urlsredis:/data
  url-shortener:
    image: p3ntest/url-shortener-redis
    environment:
      - REDIS=redis://urlredis
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - GOOGLE_KEY=${GOOGLE_KEY}
    depends_on:
      - urlredis
    labels:
      - "traefik.http.routers.urlshortener.rule=Host(`u.${HOST}`, `url.${HOST}`)"
      - "traefik.http.routers.urlshortener.tls=${USE_TLS}"
      - "traefik.http.routers.urlshortener.tls.certresolver=letsencrypt"

  # Next Cloud
  nextcloud:
    image: nextcloud
    labels:
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.${HOST}`)"
      - "traefik.http.routers.nextcloud.tls=${USE_TLS}"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
    volumes:
      - nextcloud:/var/www/html

  # Wiki
  wikidb:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ${DATABASE_SECRET}
      POSTGRES_USER: wikijs
    restart: unless-stopped
    volumes:
      - wikidbdata:/var/lib/postgresql/data
  wikijs:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - wikidb
    environment:
      DB_TYPE: postgres
      DB_HOST: wikidb
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${DATABASE_SECRET}
      DB_NAME: wiki
    restart: unless-stopped
    labels:
      - "traefik.http.routers.wikijs.rule=Host(`wiki.${HOST}`)"
      - "traefik.http.routers.wikijs.tls=${USE_TLS}"
      - "traefik.http.routers.wikijs.tls.certresolver=letsencrypt"

  # File Sharing
  youtransfer:
    image: remie/youtransfer:stable
    restart: unless-stopped
    volumes:
      - ./youtransfer:/opt/youtransfer/config
      - youtransferuploads:/opt/youtransfer/uploads
    ports:
      - 5000:5000
    labels:
      - "traefik.http.routers.youtransfer.rule=Host(`files.${HOST}`)"
      - "traefik.http.routers.youtransfer.tls=${USE_TLS}"
      - "traefik.http.routers.youtransfer.tls.certresolver=letsencrypt"

volumes:
  urlsredis:
  wikidbdata:
  nextcloud:
    external: true
  youtransferuploads:
    driver: local
    driver_opts:
      o: "size=5000m"
      device: tmpfs
      type: tmpfs

networks:
  # Externally exposing networks to hook into proxy
  traefik_proxy:
    external: true
